#!/bin/bash -e
# regenerate rhodecode secret keys and mysql password

. /etc/default/inithooks

APPNAME=rhodecode
WEBROOT=/var/www/$APPNAME

RABBITMQ_RUNNING=$(/etc/init.d/rabbitmq-server status > /dev/null; echo $?)

if [ "$RABBITMQ_RUNNING" != "0" ]; then
    rm -R /var/lib/rabbitmq/mnesia
    /etc/init.d/rabbitmq-server start
else
    /etc/init.d/rabbitmq-server stop
    rm -R /var/lib/rabbitmq/mnesia
    /etc/init.d/rabbitmq-server start
fi

# rabbitmq secret
PASSWORD=$(mcookie)
CONF=$WEBROOT/production.ini
sed -i "s|broker\.password.*|broker.password = $PASSWORD|" $CONF
rabbitmqctl add_user celeryuser $PASSWORD
rabbitmqctl add_vhost celeryvhost
rabbitmqctl set_permissions -p celeryvhost celeryuser ".*" ".*" ".*"

if [ "$RABBITMQ_RUNNING" != "0" ]; then
    /etc/init.d/rabbitmq-server stop
fi

# rhodecode uuid and session secret
CONF=$WEBROOT/production.ini
sed -i "s|app_instance_uuid.*|app_instance_uuid = $(mcookie)|" $CONF
sed -i "s|beaker\.session\.secret.*|beaker.session.secret = $(mcookie)|" $CONF

# regen mysql password
PASSWORD=$(mcookie)
CONF=$WEBROOT/production.ini
sed -i "s|mysql://.*@|mysql://${APPNAME}:${PASSWORD}@|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=$APPNAME --pass="$PASSWORD"

# remove innodb logfiles (workarounds really weird bug, may not be needed?)
rm -f /var/lib/mysql/ib_logfile*

