#!/bin/sh

### BEGIN INIT INFO
# Provides:          paster
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the paster celeryd process
# Description:       starts paster 
### END INIT INFO
 
 
PROJECT=/var/www/rhodecode
PID_DIR=/var/run
PID_FILE=$PID_DIR/celeryd/pid
LOG_FILE=/var/log/celeryd/celeryd.log
USER=www-data
GROUP=www-data
PROD_FILE=$PROJECT/production.ini
RET_VAL=0

PASTER_BIN=$PROJECT/venv/bin/paster
 
start()
{
      if [ ! -f $PID_FILE ]; then #process isn't running probably
              echo Attempting to start celeryd paste script...  forking it up with \&
              su -c "$PASTER_BIN celeryd $PROD_FILE --pidfile=$PID_FILE --logfile=$LOG_FILE &" $USER
              while [ ! -f $PID_FILE ]; do sleep 1 && echo .; done
              echo Done. PID is $(cat $PID_FILE).
      else
              echo The celeryd paste script has filed a paste PID $(cat $PID_FILE)
              echo It\'s likely started already at that PID.
      fi
}
stop()
{
       if [ -f $PID_FILE ]; then #process is running probably
              echo sending SIGINT to the process $(cat $PID_FILE) to trigger a "Warm shutdown"
              pypasteceleryPID=$(cat $PID_FILE)
              kill -s INT $pypasteceleryPID
              echo Waiting for process to die...
              #umm... yea! http://stackoverflow.com/questions/696839/how-do-i-write-a-bash-script-to-restart-a-process-if-it-dies
              while [ -f $PID_FILE ]; do sleep 1 && echo .; done
              #echo Truncating $LOG_FILE to entries from last run only.
              #sed -i '1,'$(expr $(grep -n -e "^----\s\*\*\*\*\s-----" $LOG_FILE | cut -d':' -f1 | awk '$1 > max { max=$1 }; END { print max }') - 1)'d' $LOG_FILE
      else
              echo $PID_FILE doesn\'t exist, so the celeryd paste script was not used to execute celeryd if celeryd is actually running.
              echo Otherwise it isn\'t running.
      fi

}
status()
{
     if [ -f $PID_FILE ]; then
              echo celeryd paste script is running as PID $(cat $PID_FILE)
              tail -n 20 $LOG_FILE
      else
              echo celeryd paste script isn\'t running.
      fi

}

case "$1" in
start)
    start
 
;;
stop)
    stop
 
;;
restart)
    stop
    start
 
;;
status)
    status

;;
*)
echo $"Usage: $0 {start|stop|restart|status}"
exit 1
esac
